#!/bin/sh

GIT_DIR="$HOME/Code/zomboban.git"
WORK_TREE="$HOME/Code/zomboban"
DEPLOY_BRANCH=main
DEPLOY_LOG=/tmp/deploy.log

export NODE_ENV=production
export BASE_URL=/game

while read -r oldrev newrev ref; do
  if [ "$ref" = "refs/heads/$DEPLOY_BRANCH" ]; then
    echo "Deploying main branch..." >> "$DEPLOY_LOG"
    git --work-tree="$WORK_TREE" --git-dir="$GIT_DIR" checkout -f && cd "$WORK_TREE" && yarn install --immutable >> $DEPLOY_LOG && yarn build >> $DEPLOY_LOG && pm2 restart all >> $DEPLOY_LOG
  else
    echo "Ref $ref successfully received.  Doing nothing: only the $DEPLOY_BRANCH branch may be deployed on this server." >> "$DEPLOY_LOG"
  fi
done
