// TODO all of this can go away now
export enum ReservedEntity {
  CAMERA,
  FLOOR_IMAGE,
  WALL_IMAGE,
  CRATE_IMAGE,
  PLAYER_DOWN_IMAGE,
  ZOMBIE_SWAY_ANIMATION,
  POTION_SPIN_ANIMATION,
  EDITOR_NORMAL_CURSOR_IMAGE,
  EDITOR_REPLACE_CURSOR_IMAGE,
  EDITOR_ORIENT_CURSOR_IMAGE,
  SCORE_TEXT,
  GUI_BUTTON_IMAGE,
  HAND_CURSOR_IMAGE,
}
